//Title: Dry Run....
//Type: I like Harambe, NOBODY HATES HARAMBE! HOW CAN YOU?!
#include <cstdio>
char str[100];
//LET ME HAVE SOME CHICKENWINGS PLS THIS YEAR NEED CHICKENWINGS FOR FOOD
int T;
int main(){
	//ASJKLFDJAKSLDJFLSJDasd
	scanf("%d", &T);
	/*WTF IS THIS DRY RUN*/
	while(T--){
		//HEY I LIKE PIE
		scanf("%s", &str);
		//I HATE YOU!!!!
		printf("I like %s.\n", str);
		//YUM
	}
	//ABCDEFGHJIKLMNOPQRSTUVWXYZMZMZMZMZMZMZMZMZ
	//MEMES FOR DAYS
	//DICKS OUT FOR HARAMBE
	//DO NOT RETURN 0
	//WHAT IS 0
	//RE:0 LIFE IN A RETURNED WORLD STARTING FROM 1
	//RE:1 LIFE IN A DIFFERENT WORLD STARTING FROM ABCDEFGHIJKLMNOPQRSTUVWXYZASDASDASDASDASDADS
	return 0;
}